services:
  web:
    image: php:8.4-apache
    restart: always
    build: .
    container_name: ${APP_KEY}-apache
    volumes:
      - ./${APACHE_HTDOCS}:/var/www/html
      - ./${APP_CONFIG}/php/php.ini:/usr/local/etc/php/php.ini
      - ./${APP_CONFIG}/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "${APACHE_PORT}:80"
    networks:
      - pxf-network
    depends_on:
      - db
      - redis

  db:
    image: mariadb:${MARIADB_VERSION}
    restart: always
    container_name: ${APP_KEY}-db
    environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MARIADB_LOCAL_DIR}${MARIADB_DATA_DIR}:/var/lib/mysql
      - ${MARIADB_LOCAL_DIR}${MARIADB_CONF_DIR}:/etc/mysql/conf.d
      - ${MARIADB_LOCAL_DIR}${MARIADB_ETC_DIR}:/etc/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - pxf-network

  redis:
    image: redis:7
    restart: always
    container_name: ${APP_KEY}-redis
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - pxf-network

networks:
  pxf-network:
    driver: bridge

volumes:
  db_data:
